apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: gobby-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gobby-api
  template:
    metadata:
      labels:
        app: gobby-api
    spec:
      containers:
        - name: gobby-api
          image: tomrt/gobby:latest
          ports:
            - containerPort: 80
